spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moabook?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: '2'
    driver-class-name: org.postgresql.Driver
    username: xonic
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
